### ISSUE TITLE
Github Action으로 SonarQube 연동

### ISSUE THREAD

**Issue by sungjun1116** [D-Caffeination/D-Caffeination-backend#2]
# Github Action으로 SonarQube 연동

## Create GitHub Secrets
In your GitHub repository, go to Settings > Secrets and create two new secrets:
   - Click on New repository secret
   - In the Name field, enter **SONAR_TOKEN**
   - In the Value field, enter an existing token, or a newly generated one
   - Click on Add secret
   ---------------------------------------
   - Click on New repository secret
   - In the Name field, enter **SONAR_HOST_URL**
   - In the Value field, enter http://43.200.113.118:9000 
   - Click on Add secret

## Create Workflow YAML File(Gradle 기준)

Update your build.gradle file with the org.sonarqube plugin and it's configuration:
```
plugins {
  id "org.sonarqube" version "3.4.0.2513"
}

sonarqube {
  properties {
    property "sonar.projectKey", "decaf-backend"
  }
}
```

Create or update your .github/workflows/build.yml YAML file with the following content:
```
name: Build
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
         # overwrite-settings: false
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonarqube --info
```
